<!--
%\VignetteEngine{knitr}
%\VignetteIndexEntry{Make wasp data}
-->

First, you need to:
[Install the OS X command line tools](http://www.rstudio.com/ide/docs/packages/prerequisites) (for a C++ compiler)

```{r}
install.packages("Rcpp", type = "source")
install.packages("devtools")
devtools::install_github("jackets", "seananderson")
devtools::install_github("dplyr")
```

Restart R if you've previously loaded plyr.

Then

```{r}
library(jackets)
library(data.table)
```

To read and save the `.rda` files in Dropbox, first set your working
directory to the `wasp-trips/data` folder before running this code:

```{r, eval=FALSE}
load("wasps1.rda")
wasps1$uid_group <- wasps1$uid
wasps1_dt <- dplyr::group_by(as.data.table(wasps1), uid_group)
rm(wasps1)
wasps1_trips <- dplyr::do(wasps1_dt, function(x) get_wasp_trips(x,
    diff_address_home = -1, diff_address_away = 1,
    correct_time_stamps = FALSE, print_progress = TRUE))
rm(wasps1_dt)
wasps1_trips <- do.call("rbind", wasps1_trips)
wasps1_trips <- as.data.frame(wasps1_trips)

load("wasps2.rda")
wasps2$uid_group <- wasps2$uid
wasps2_dt <- dplyr::group_by(as.data.table(wasps2), uid_group)
rm(wasps2)
wasps2_trips <- dplyr::do(wasps2_dt, function(x) get_wasp_trips(x,
    diff_address_home = 2, diff_address_away = -2,
    correct_time_stamps = TRUE, print_progress = TRUE))
rm(wasps2_dt)
wasps2_trips <- do.call("rbind", wasps2_trips)
wasps2_trips <- as.data.frame(wasps2_trips)

wasps1_trips$group <- 1
wasps2_trips$group <- 2
wasp <- rbind(wasps1_trips, wasps2_trips)
rm(wasps1_trips, wasps2_trips)

row.names(wasp) <- NULL

save(wasp, file = "wasp.rda")
```

We can now load the `wasp.rda` file from within the package with:

```{r}
load("wasp.rda")
```

We have to unload dplyr to load plyr:

```{r}
wasp$time_trunc <- as.POSIXct(trunc(wasp$time, "days"))
wasp$hour_of_day <- as.numeric(difftime(wasp$time, wasp$time_trunc,
    units = "hours"))
```

Now merge in the tag-caste data

```{r}
load("cohorts_1.rda")
cohorts_1$caste <- as.character(cohorts_1$caste)
cohorts_1$date_tagged <- as.character(cohorts_1$date_tagged)
cohorts_2 <- read.csv("cohorts.csv", stringsAsFactors = FALSE)
cohorts_1$group <- 1
cohorts_2$group <- 2
cohorts <- rbind(cohorts_1, cohorts_2)
cohorts$date_tagged <- strptime(cohorts$date_tagged, format = "%Y-%m-%d")
cohorts$date_tagged <- as.POSIXct(cohorts$date_tagged)

# Create a transformed uid column that matches the tag format:
wasp <- transform(wasp, tag = paste0(substr(uid, 1, 2), substr(uid, 4, 5)))
wasp$uid <- NULL

wasp <- plyr::join(wasp, cohorts, by = c("tag", "group"))
```

```{r}
library(ggplot2)
ggplot(na.omit(wasp), aes(hour_of_day)) + geom_histogram(aes(fill = trips)) +
facet_grid(caste~group, scales = "free_y")
```

